[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.install]
cmds = ["dotnet restore TMS.sln"]

[phases.build]
cmds = ["dotnet publish TMS.API/TMS.API.csproj --no-restore -c Release -o out"]

[start]
cmd = "./out/TMS.API"